-- Enable the pgvector extension to work with embedding vectors
CREATE EXTENSION IF NOT EXISTS vector;

-- Create a table for the Knowledge Base (Financial Data)
-- Create a table for the Knowledge Base (Financial Data)
CREATE TABLE public.knowledge_base (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text,
  metadata jsonb,
  embedding vector(768)
);

-- Existing tables (Refined for the context)
CREATE TABLE public.agents (
  agent_id text NOT NULL,
  name text,
  languages ARRAY,
  specialization text,
  performance_score double precision,
  performance_stats jsonb DEFAULT '{}'::jsonb,
  embedding vector(768), -- Changed to vector type
  email text,
  password text DEFAULT '123456'::text,
  CONSTRAINT agents_pkey PRIMARY KEY (agent_id)
);

CREATE TABLE public.investors (
  investor_id text NOT NULL,
  name text,
  age integer,
  city text,
  occupation text,
  risk_appetite text,
  sip_capacity integer,
  preferred_language text,
  created_at text,
  gender text,
  tier text,
  monthly_income_est integer,
  last_activity_date text,
  embedding vector(768), -- Changed to vector type
  assigned_agent_id text,
  ai_analysis_cache jsonb,
  CONSTRAINT investors_pkey PRIMARY KEY (investor_id)
);

-- Interactions table for logging calls
CREATE TABLE public.interactions (
  interaction_id text NOT NULL,
  investor_id text,
  agent_id text,
  date date,
  outcome text,
  objections_raised jsonb,
  duration_sec integer,
  sentiment text,
  transcript text, -- Added for storing the full call text
  report_summary jsonb, -- Added for storing the generated report
  CONSTRAINT interactions_pkey PRIMARY KEY (interaction_id),
  CONSTRAINT interactions_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.investors(investor_id),
  CONSTRAINT interactions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id)
);

-- Function to match documents in knowledge_base
create or replace function match_documents (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    knowledge_base.id,
    knowledge_base.content,
    knowledge_base.metadata,
    1 - (knowledge_base.embedding <=> query_embedding) as similarity
  from knowledge_base
  where 1 - (knowledge_base.embedding <=> query_embedding) > match_threshold
  order by knowledge_base.embedding <=> query_embedding
  limit match_count;
end;
$$;
